using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace YummyApp
{
    /// <summary>
    /// Interaction logic for extra.xaml
    /// </summary>
    public partial class extra : Window
    {
        yummyDatabaseDataContext dc = new yummyDatabaseDataContext();
        public extra()
        {
            InitializeComponent();
            dgRecipes.AutoGeneratedColumns += DgRecipes_AutoGeneratedColumns;
            refreshRecipies();
        }

        private void DgRecipes_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgRecipes.Columns[0].Visibility = Visibility.Hidden;
        }

        private void btnAddRecipe_Click(object sender, RoutedEventArgs e)
        {
            AddRecipe addRecipe = new AddRecipe();
            addRecipe.ShowDialog();
            refreshRecipies();
        }

        private void btnUpdateRecipe_Click(object sender, RoutedEventArgs e)
        {
            AddRecipe addRecipe = new AddRecipe((dgRecipes.SelectedItem as dynamic).RecipeId);
            //AddRecipe addRecipe = new AddRecipe((dgRecipes.SelectedItem as Recipe).RecipeId);
            addRecipe.ShowDialog();
            refreshRecipies();
        }

        private void refreshRecipies()
        {
            dc = new yummyDatabaseDataContext();
            dgRecipes.ItemsSource = null;
            dgRecipes.ItemsSource = dc.Recipes.Select(recipe => new { recipe.RecipeId, recipe.Name, recipe.PrepTime, recipe.Serving, Category = recipe.Category1.CategoryName });
        }
    }
}
